# Program:	IPOPD client Makefile
#
# Author:	Mark Crispin
#		Networks and Distributed Computing
#		Computing & Communications
#		University of Washington
#		Administration Building, AG-44
#		Seattle, WA  98195
#		Internet: MRC@CAC.Washington.EDU
#
# Date:		28 October 1990
# Last Edited:	30 November 1995
#
# Copyright 1995 by the University of Washington
#
#  Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted, provided
# that the above copyright notice appears in all copies and that both the
# above copyright notice and this permission notice appear in supporting
# documentation, and that the name of the University of Washington not be
# used in advertising or publicity pertaining to distribution of the software
# without specific, written prior permission.  This software is made
# available "as is", and
# THE UNIVERSITY OF WASHINGTON DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
# WITH REGARD TO THIS SOFTWARE, INCLUDING WITHOUT LIMITATION ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND IN
# NO EVENT SHALL THE UNIVERSITY OF WASHINGTON BE LIABLE FOR ANY SPECIAL,
# INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, TORT
# (INCLUDING NEGLIGENCE) OR STRICT LIABILITY, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


C = ..\c-client
CCLIENTLIB = $C\cclient.lib
LIBS = $(CCLIENTLIB) wsock32.lib winmm.lib advapi32.lib netapi32.lib libc.lib
CFLAGS= -I$C /MT /W3 /DWIN32 -nologo $(EXTRACFLAGS)

ipopd: ipop2d ipop3d

ipop2d: $(CCLIENTLIB) ipop2d.obj
	LINK /NOLOGO /DEF:ipop2d.def ipop2d.obj $(LIBS)

ipop3d: $(CCLIENTLIB) ipop3d.obj
	LINK /NOLOGO /DEF:ipop3d.def ipop3d.obj $(LIBS)

ipop2d.obj: $C\mail.h $C\misc.h $C\osdep.h

ipop3d.obj: $C\mail.h $C\misc.h $C\osdep.h

$(CCLIENTLIB):
	@echo Make c-client first
	false

clean:
	RM /f /x *.obj *.exe *.lib *.exp

# A monument to a hack of long ago and far away...
love:
	@echo not war?
