# ========================================================================
# Copyright 1988-2006 University of Washington
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# 
# ========================================================================


# Program:	IPOPD Makefile for Windows 9x and Windows NT
#
# Author:	Mark Crispin
#		Networks and Distributed Computing
#		Computing & Communications
#		University of Washington
#		Administration Building, AG-44
#		Seattle, WA  98195
#		Internet: MRC@CAC.Washington.EDU
#
# Date:		28 October 1990
# Last Edited:	30 August 2006


C = ..\c-client
CCLIENTLIB = $C\cclient.lib
LIBS = $(CCLIENTLIB) ws2_32.lib winmm.lib advapi32.lib
OSCOMPAT = /DWIN32 /D_WIN32_WINNT=0x0400
VSCOMPAT = /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE
CFLAGS= -I$C /MT /W3 $(OSCOMPAT) $(VSCOMPAT) -nologo $(EXTRACFLAGS)


ipopd: ipop2d ipop3d

ipop2d: $(CCLIENTLIB) ipop2d.obj
	LINK /NOLOGO ipop2d.obj $(LIBS)

ipop3d: $(CCLIENTLIB) ipop3d.obj
	LINK /NOLOGO ipop3d.obj $(LIBS)

ipop2d.obj: $C\mail.h $C\misc.h $C\osdep.h

ipop3d.obj: $C\mail.h $C\misc.h $C\osdep.h

$(CCLIENTLIB):
	@echo Make c-client first
	false

clean:
	del *.obj *.exe *.lib *.exp || rem

# A monument to a hack of long ago and far away...
love:
	@echo not war?
